# Generated by Django 5.2.7 on 2025-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_path_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
