# Generated by Django 5.2.7 on 2025-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_image1_vehicle_image2_vehicle_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='safety_rating',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='torque',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
